services:
  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    hostname: gh5
    environment:
      - TS_AUTHKEY=<TAILSCALE_AUTH_KEY>
      - TS_ACCEPT_DNS=true
      - TS_ROUTES=10.69.1.0/24
      - TS_EXTRA_ARGS=--advertise-exit-node
    volumes:
      - /var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
    privileged: true # Optional: sometimes needed for /dev/net/tun access
